"""add_machine_management_permissions

Revision ID: 0fd8b00290b9
Revises: c29bb578671d
Create Date: 2025-05-14 11:48:09.890015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd8b00290b9'
down_revision = 'c29bb578671d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_index('idx_machine_serial_number')

    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_index('idx_offer_number')

    with op.batch_alter_table('periodic_maintenance', schema=None) as batch_op:
        batch_op.drop_index('idx_periodic_maintenance_interval')
        batch_op.drop_index('idx_periodic_maintenance_model')

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_search_machines', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_add_machines', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_add_maintenance', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_username', ['username'], unique=False)

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_column('can_add_maintenance')
        batch_op.drop_column('can_add_machines')
        batch_op.drop_column('can_search_machines')

    with op.batch_alter_table('periodic_maintenance', schema=None) as batch_op:
        batch_op.create_index('idx_periodic_maintenance_model', ['machine_model'], unique=False)
        batch_op.create_index('idx_periodic_maintenance_interval', ['maintenance_interval'], unique=False)

    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.create_index('idx_offer_number', ['offer_number'], unique=False)

    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.create_index('idx_machine_serial_number', ['serial_number'], unique=False)

    # ### end Alembic commands ###
