"""Initial migration

Revision ID: 1672fe721f7f
Revises: 
Create Date: 2025-05-13 16:38:24.471696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1672fe721f7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('responsible_service', sa.String(length=200), nullable=True),
    sa.Column('delivery_photos', sa.String(length=500), nullable=True),
    sa.Column('delivery_document', sa.String(length=500), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('alternate_part_code', sa.String(length=50), nullable=True),
    sa.Column('price_eur', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_code')
    )
    op.create_table('periodic_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_model', sa.String(length=100), nullable=False),
    sa.Column('filter_name', sa.String(length=100), nullable=False),
    sa.Column('filter_part_code', sa.String(length=50), nullable=False),
    sa.Column('alternate_part_code', sa.String(length=50), nullable=True),
    sa.Column('original_price_eur', sa.Float(), nullable=False),
    sa.Column('alternate_price_eur', sa.Float(), nullable=True),
    sa.Column('maintenance_interval', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('motor_pdf_url', sa.String(length=200), nullable=True),
    sa.Column('yedek_parca_pdf_url', sa.String(length=200), nullable=True),
    sa.Column('operator_pdf_url', sa.String(length=200), nullable=True),
    sa.Column('service_pdf_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_maintenance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('invoice_file', sa.String(length=200), nullable=True),
    sa.Column('part_image', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_number', sa.String(length=50), nullable=False),
    sa.Column('machine_model', sa.String(length=100), nullable=False),
    sa.Column('maintenance_interval', sa.String(length=50), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.Column('filter_type', sa.String(length=50), nullable=False),
    sa.Column('customer_first_name', sa.String(length=100), nullable=False),
    sa.Column('customer_last_name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('offeror_name', sa.String(length=100), nullable=False),
    sa.Column('labor_cost', sa.Float(), nullable=False),
    sa.Column('travel_cost', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('discount_type', sa.String(length=50), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('pdf_file_path', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_number')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_view_parts', sa.Boolean(), nullable=True),
    sa.Column('can_edit_parts', sa.Boolean(), nullable=True),
    sa.Column('can_view_faults', sa.Boolean(), nullable=True),
    sa.Column('can_add_solutions', sa.Boolean(), nullable=True),
    sa.Column('can_view_catalogs', sa.Boolean(), nullable=True),
    sa.Column('can_view_maintenance', sa.Boolean(), nullable=True),
    sa.Column('can_edit_maintenance', sa.Boolean(), nullable=True),
    sa.Column('can_view_contact', sa.Boolean(), nullable=True),
    sa.Column('can_view_purchase_prices', sa.Boolean(), nullable=True),
    sa.Column('can_view_warranty', sa.Boolean(), nullable=True),
    sa.Column('can_view_accounting', sa.Boolean(), nullable=True),
    sa.Column('can_view_periodic_maintenance', sa.Boolean(), nullable=True),
    sa.Column('can_view_admin_panel', sa.Boolean(), nullable=True),
    sa.Column('can_create_offers', sa.Boolean(), nullable=True),
    sa.Column('can_view_offers', sa.Boolean(), nullable=True),
    sa.Column('can_upload_excel', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_code_url', sa.String(length=200), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code_url')
    )
    op.create_table('warranty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('document_url', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('fault_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_item.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('amount_eur', sa.Float(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('document_url', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['machine_maintenance_record.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('maintenance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('invoice_file', sa.String(length=200), nullable=True),
    sa.Column('image_file', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fault_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fault_id', sa.Integer(), nullable=False),
    sa.Column('report_description', sa.Text(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fault_id'], ['fault.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fault_solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fault_report_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('part_codes', sa.String(length=200), nullable=True),
    sa.Column('media_file', sa.String(length=200), nullable=True),
    sa.Column('machine_model', sa.String(length=100), nullable=False),
    sa.Column('fault_type', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fault_report_id'], ['fault_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fault_solution')
    op.drop_table('invoice_approval')
    op.drop_table('fault_report')
    op.drop_table('maintenance_record')
    op.drop_table('invoice')
    op.drop_table('fault')
    op.drop_table('warranty')
    op.drop_table('qr_code')
    op.drop_table('permission')
    op.drop_table('offer')
    op.drop_table('machine_maintenance_record')
    op.drop_table('catalog_item')
    op.drop_table('announcement')
    op.drop_table('user')
    op.drop_table('periodic_maintenance')
    op.drop_table('part')
    op.drop_table('machine')
    op.drop_table('catalog')
    # ### end Alembic commands ###
