"""initial_migration

Revision ID: f48f0a8538ae
Revises: 
Create Date: 2025-05-08 14:11:50.729723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48f0a8538ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_index('idx_machine_serial_number')

    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_index('idx_offer_number')

    with op.batch_alter_table('periodic_maintenance', schema=None) as batch_op:
        batch_op.drop_index('idx_periodic_maintenance_interval')
        batch_op.drop_index('idx_periodic_maintenance_model')

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view_offers', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_username', ['username'], unique=False)

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_column('can_view_offers')

    with op.batch_alter_table('periodic_maintenance', schema=None) as batch_op:
        batch_op.create_index('idx_periodic_maintenance_model', ['machine_model'], unique=False)
        batch_op.create_index('idx_periodic_maintenance_interval', ['maintenance_interval'], unique=False)

    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.create_index('idx_offer_number', ['offer_number'], unique=False)

    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.create_index('idx_machine_serial_number', ['serial_number'], unique=False)

    # ### end Alembic commands ###
